'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';

const prettyStatus={published_confirmed:'Publicado',prepared:'Preparado',needs_editorial_review:'Revisão editorial',duplicate_blocked:'Duplicata bloqueada',pending:'Agendado no servidor',blocked_auth:'Sem conexão LinkedIn',dispatching:'Enviando',submitted_unconfirmed:'Enviado, aguardando confirmação',uncertain:'Envio incerto',cancelled:'Cancelado'};
function localInput(iso){if(!iso)return '';const d=new Date(iso);const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
export default function Home(){
  const [posts,setPosts]=useState([]),[status,setStatus]=useState({linkedinConnected:false,schedulerRunning:false});
  const [selected,setSelected]=useState(null),[filter,setFilter]=useState('all'),[topic,setTopic]=useState('all'),[query,setQuery]=useState('');
  const [date,setDate]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const [a,b]=await Promise.all([fetch('/api/posts',{cache:'no-store'}),fetch('/api/status',{cache:'no-store'})]);const pa=await a.json(),pb=await b.json();setPosts(pa.posts||[]);setStatus(pb);}catch(e){setMessage(`Servidor indisponível: ${e.message}`)}},[]);
  useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[load]);
  const topics=useMemo(()=>[...new Set(posts.map(p=>p.topic))].sort(),[posts]);
  const visible=posts.filter(p=>{const state=p.status==='published_confirmed'?'published':'prepared';return(filter==='all'||filter===state)&&(topic==='all'||topic===p.topic)&&`${p.title} ${p.topic} ${p.body}`.toLowerCase().includes(query.toLowerCase())});
  const published=posts.filter(p=>p.status==='published_confirmed').length;
  const prepared=posts.length-published;
  const current=selected&&posts.find(p=>p.id===selected.id)||selected;
  async function action(mode){if(!current)return;setBusy(true);setMessage('');try{const runAt=mode==='schedule'?new Date(date).toISOString():undefined;const r=await fetch('/api/dispatches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({postId:current.id,mode,runAt})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Falha no pedido');setMessage(mode==='now'?'Pedido recebido pelo servidor. A confirmação do LinkedIn aparecerá aqui.':'Agendamento gravado no SQLite. O servidor precisa estar ligado e o LinkedIn conectado no horário.');await load();}catch(e){setMessage(e.message)}finally{setBusy(false)}}
  async function changeSchedule(mode){if(!current?.dispatchId)return;setBusy(true);setMessage('');try{const r=await fetch(`/api/dispatches/${current.dispatchId}`,{method:mode==='cancel'?'DELETE':'PATCH',headers:{'Content-Type':'application/json'},body:mode==='cancel'?undefined:JSON.stringify({runAt:new Date(date).toISOString()})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Falha na alteração');setMessage(mode==='cancel'?'Agendamento cancelado.':'Novo horário salvo.');await load();}catch(e){setMessage(e.message)}finally{setBusy(false)}}
  return <div className="shell"><header className="top"><div><h1>Publicações LinkedIn</h1><p>{status.publicMode?'Explore pautas, fontes e publicações do meu acervo de tecnologia.':'Escolha uma pauta, revise texto e capa, publique agora ou programe um horário.'}</p></div><div className="session"><div className={'connection '+(status.publicMode||status.linkedinConnected?'ready':'blocked')}><span className="dot"/>{status.publicMode?'Catálogo público':status.linkedinConnected?'LinkedIn conectado':'LinkedIn não conectado'}</div>{!status.publicMode&&<form method="post" action="/api/auth/logout"><button className="logout" type="submit">Sair</button></form>}</div></header>
    {status.publicMode?<div className="notice"><strong>Catálogo público.</strong> Este ambiente é somente leitura. Publicações e agendamentos são operados em um ambiente privado.</div>:!status.linkedinConnected&&<div className="notice"><strong>Publicação direta indisponível.</strong> Para ativá-la, conecte uma aplicação LinkedIn com permissão de publicação. Os agendamentos podem ser registrados agora, mas não serão enviados até a conexão estar configurada. Nenhum clique será marcado como publicado sem retorno da plataforma.</div>}
    <section className="summary"><div><b>{posts.length}</b><span>pautas no acervo</span></div><div><b>{published}</b><span>publicadas</span></div><div><b>{prepared}</b><span>não publicadas</span></div><div><b>{new Set(posts.map(p=>p.topic)).size}</b><span>temas catalogados</span></div></section>
    <section className="controls"><input aria-label="Buscar publicações" placeholder="Buscar publicação ou tema" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filtrar tema" value={topic} onChange={e=>setTopic(e.target.value)}><option value="all">Todos os temas</option>{topics.map(t=><option value={t} key={t}>{t}</option>)}</select><div className="tabs">{[['all','Todas'],['published','Publicadas'],['prepared','Preparadas']].map(([k,v])=><button key={k} className={filter===k?'active':''} onClick={()=>setFilter(k)}>{v}</button>)}</div></section>
    <main className="grid">{visible.map(p=><article className="card" key={p.id}><button className="image-button" aria-label={`Abrir ${p.title}`} onClick={()=>{setSelected(p);setDate(p.runAt?localInput(p.runAt):'');setMessage('')}}><img src={`/api/covers/${encodeURIComponent(p.id)}`} alt={`Capa: ${p.title}`}/></button><div className="card-content"><div className="line"><span className={'badge '+(p.status==='published_confirmed'?'published':'prepared')}>{prettyStatus[p.status]||p.status}</span><span>{p.topic} · {p.origin}</span></div><h2>{p.title}</h2><p className="card-snippet">{p.body.slice(0,135)}{p.body.length>135?'…':''}</p>{p.dispatchState&&<div className="dispatch">{prettyStatus[p.dispatchState]||p.dispatchState}{p.runAt&&` · ${new Date(p.runAt).toLocaleString('pt-BR')}`}</div>}<button className="open" onClick={()=>{setSelected(p);setDate(p.runAt?localInput(p.runAt):'');setMessage('')}}>Abrir publicação <span aria-hidden="true">→</span></button></div></article>)}</main>
    {!visible.length&&<p className="empty">Nenhuma pauta corresponde aos filtros.</p>}
    {current&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="dialog" role="dialog" aria-modal="true" aria-label={current.title}><div className="dialog-head"><div><span>{current.topic} · {current.origin}</span><h2>{current.title}</h2></div><button className="close" aria-label="Fechar" onClick={()=>setSelected(null)}>×</button></div><div className="dialog-scroll"><img className="dialog-cover" src={`/api/covers/${encodeURIComponent(current.id)}`} alt={`Capa: ${current.title}`}/>{!status.publicMode&&<p className={'cover-check '+(current.coverSafe?'ok':'bad')}>{current.coverSafe?'Capa PNG sem C2PA detectado':'Capa com C2PA ou formato não validado — envio bloqueado'}</p>}<pre className="body-text">{current.body}</pre>{current.sourceUrl&&<p>Fonte: <a href={current.sourceUrl} target="_blank" rel="noopener noreferrer">abrir fonte</a></p>}{current.permalink&&<p>Publicação: <a href={current.permalink} target="_blank" rel="noopener noreferrer">abrir no LinkedIn</a></p>}</div>{!status.publicMode&&<div className="dialog-actions">{current.status==='prepared'&&<><button className="primary" disabled={busy||!status.linkedinConnected||!current.coverSafe||['pending','dispatching','submitted_unconfirmed','blocked_auth','uncertain'].includes(current.dispatchState)} onClick={()=>action('now')}>Publicar agora</button><div className="schedule"><label htmlFor="date">Agendar para</label><input id="date" type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/><button disabled={busy||!date||!current.coverSafe||['dispatching','submitted_unconfirmed'].includes(current.dispatchState)} onClick={()=>current.dispatchState==='pending'||current.dispatchState==='blocked_auth'?changeSchedule('reschedule'):action('schedule')}>{current.dispatchState==='pending'||current.dispatchState==='blocked_auth'?'Alterar horário':'Agendar'}</button>{['pending','blocked_auth','uncertain'].includes(current.dispatchState)&&<button disabled={busy} onClick={()=>changeSchedule('cancel')}>Cancelar</button>}</div></>}{message&&<p className="message" role="status">{message}</p>}{current.dispatchState==='submitted_unconfirmed'&&<p className="message">O LinkedIn aceitou o envio pela API. Confirme a publicação no perfil antes de considerá-la concluída.</p>}{current.dispatchState==='uncertain'&&<p className="message">Envio incerto. Consulte o perfil antes de qualquer nova tentativa.</p>}</div>}</section></div>}
  </div>
}
